---
title: "COVID Hospitalizations"
subtitle: "Hospitalizations by Type and Available ICU Beds for Lancaster and Philadelphia Counties"
output:
  rmarkdown::html_document:
    theme: flatly
output_dir: "docs"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
library(jsonlite)
library(tidyr)
library(zoo)
library(plotly)
library(kableExtra)
library(data.table)
library(lubridate)
library(plotly)

knitr::knit_hooks$set(
   warning = function(x, options) {
     paste('\n\n<div class="alert alert-warning">',
           gsub('##', '\n', gsub('^##\ Warning:', '**Warning**', x)),
           '</div>', sep = '\n')
   }
)


options(scipen = 999) 
```

*Notice: This website is a personal project and is not intended for public use. Please do not use this site as a source for reliable information on COVID.*

```{r, echo=FALSE, results = 'asis'}

today <- today()
cat("Site last updated ", format(today, format= "%B %d %Y"))
```


```{r read in philadelphia}

url <- URLencode("https://data.pa.gov/resource/kayn-sjhx.json?county=Philadelphia")

data_import <- fromJSON(url)

data_import$date <- as_datetime(data_import$date)

colnames <- colnames(data_import[3:37])

data_longer <- pivot_longer(data_import, cols = colnames, 
                            names_to = "indicator", values_to = "number") %>%
  mutate(number = as.numeric(number))

```


```{r plot philadelphia}

philadelphia <- data_longer %>% 
  filter(county == "Philadelphia", 
         indicator %in% c("date", "covid_patients", "covid_vents", 
                          "covid_patients_adult_in_icu", "icu_avail")) %>% 
  drop_na()

ggplotly(ggplot(philadelphia, aes(x = date, y = number)) + 
  geom_line(aes(color = indicator)) +
  ggtitle("Philadelphia COVID Hospitalizations") +
  theme_minimal())
```

```{r read in lancaster}

url <- URLencode("https://data.pa.gov/resource/kayn-sjhx.json?county=Lancaster")

data_import <- fromJSON(url)

data_import$date <- as_datetime(data_import$date)

colnames <- colnames(data_import[3:36])

data_longer <- pivot_longer(data_import, cols = colnames, 
                            names_to = "indicator", values_to = "number") %>%
  mutate(number = as.numeric(number))


           
```

```{r plot lancaster}

lancaster <- data_longer %>% 
  filter(county == "Lancaster", 
         indicator %in% c("date", "covid_patients", "covid_vents", 
                          "covid_patients_adult_in_icu", "icu_avail")) %>% 
  drop_na()

ggplotly(ggplot(lancaster, aes(x = date, y = number)) + 
  geom_line(aes(color = indicator)) +
  ggtitle("Lancaster COVID Hospitalizations") +
  theme_minimal())
```

```{r new pediatric cases, eval=TRUE}

download.file(url = "https://github.com/ambientpointcorp/covid19-philadelphia/archive/master.zip", destfile = "covid_archive_github.zip")

unzip(zipfile = "covid_archive_github.zip", overwrite = T)

# Stack daily files within folder and keep distinct records
build_historical_dataset <- function(data_folder) {
  list.files(path = data_folder, full.names = TRUE) %>%
    map_dfr(read_csv) %>%
    distinct() # duplicates occur when there is an extract but no data update
}

# Cases by test result and reporting dates
cases_by_age <- build_historical_dataset("covid19-philadelphia-master/cases_by_age/")

cases_under_20_complete <- cases_by_age %>% 
  filter(age == "<20") %>% 
  mutate(date = as.Date(etl_timestamp)) %>% 
   complete(date = full_seq(date, period = 1), fill = list(count = NA, age = "<20"))

cases_under_20_complete$count_imputed <- na.approx(cases_under_20_complete$count, maxgap = 7)

cases_under_20_complete <- cases_under_20_complete %>% 
  mutate(new_cases = count_imputed - lag(count_imputed, n=1),
         new_cases_7_mean = rollmean(new_cases, 7, align = "right", na.pad=TRUE)
         )

    covid_cases_under_20 <- ggplot(data = cases_under_20_complete, aes(x=date,
             y=new_cases)) +
  geom_col(fill="pink")+
  geom_line(aes(y = new_cases_7_mean), 
            color = "red", 
            size = .75)+
  labs(title="New Philadelphia COVID Cases for < 20 Population",
       y="New Cases / Day",
       x="") +
      theme_bw()
  
ggplotly(covid_cases_under_20)


```


````{r ped hospitilizations}

# Cases by test result and reporting dates
hospitilizations_by_age <- build_historical_dataset("covid19-philadelphia-master/hospitalizations_by_age/")

hospitilizations_under_20_complete <- hospitilizations_by_age %>% 
  filter(age == "<20") %>% 
  mutate(date = as.Date(etl_timestamp)) %>% 
   complete(date = full_seq(date, period = 1), fill = list(Yes = NA, age = "<20"))

#hospitilizations_under_20_complete$Yes_imputed <- #na.approx(hospitilizations_under_20_complete$Yes, maxgap = 7)

hospitilizations_under_20_complete <- hospitilizations_under_20_complete %>% 
  mutate(new_hospitilizations = Yes - lag(Yes, n=1),
         new_hospitilizations_7_mean = rollmean(new_hospitilizations, 7, align = "right", na.pad=TRUE)
         )

covid_hospitilizations_under_20 <- ggplot(data = hospitilizations_under_20_complete, aes(x=date,
             y=new_hospitilizations)) +
  geom_col(fill="pink")+
  labs(title="New Philadelphia COVID Hospitalizations for < 20 Population",
       y="New Hospitalizations",
       x="") +
      theme_bw()
  
ggplotly(covid_hospitilizations_under_20)

```
